import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const dummyPGs = [
  {
    pgname: 'Sunny Stay',
    address: '123 Andheri West, Mumbai',
    area: 'Andheri',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 6000,
    availableFor: 'Boys',
  },
  {
    pgname: 'Cozy Corner',
    address: '45 Baner Road, Pune',
    area: 'Baner',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 7000,
    availableFor: 'Girls',
  },
  {
    pgname: 'Urban Nest',
    address: '78 Koramangala 3rd Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 8000,
    availableFor: 'All',
  },
  {
    pgname: 'Comfy Homes',
    address: '15 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7500,
    availableFor: 'Boys',
  },
  {
    pgname: 'Safe Stay PG',
    address: '9 Hinjewadi Phase 1, Pune',
    area: 'Hinjewadi',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 6500,
    availableFor: 'Girls',
  },
  {
    pgname: 'Dream Home PG',
    address: '200 Andheri East, Mumbai',
    area: 'Andheri',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6000,
    availableFor: 'All',
  },
  {
    pgname: 'Relax Inn',
    address: '67 Baner Road, Pune',
    area: 'Baner',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 7000,
    availableFor: 'Boys',
  },
  {
    pgname: 'Home Away',
    address: '120 Koramangala 5th Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7500,
    availableFor: 'Girls',
  },
  {
    pgname: 'Comfort Zone',
    address: '35 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7200,
    availableFor: 'All',
  },
  {
    pgname: 'Secure Stay',
    address: '14 Hinjewadi Phase 2, Pune',
    area: 'Hinjewadi',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6800,
    availableFor: 'Boys',
  },
  {
    pgname: 'Elite PG',
    address: '250 Andheri West, Mumbai',
    area: 'Andheri',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 7000,
    availableFor: 'Girls',
  },
  {
    pgname: 'Bright Rooms',
    address: '88 Baner Road, Pune',
    area: 'Baner',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7200,
    availableFor: 'All',
  },
  {
    pgname: 'Sunshine PG',
    address: '90 Koramangala 2nd Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7300,
    availableFor: 'Boys',
  },
  {
    pgname: 'Peaceful Stay',
    address: '56 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6900,
    availableFor: 'Girls',
  },
  {
    pgname: 'Harbor PG',
    address: '22 Hinjewadi Phase 3, Pune',
    area: 'Hinjewadi',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 6700,
    availableFor: 'All',
  },
  {
    pgname: 'Nest Away',
    address: '300 Andheri East, Mumbai',
    area: 'Andheri',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 6500,
    availableFor: 'Boys',
  },
  {
    pgname: 'Blue Sky PG',
    address: '110 Baner Road, Pune',
    area: 'Baner',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7100,
    availableFor: 'Girls',
  },
  {
    pgname: 'Cozy Stay',
    address: '180 Koramangala 1st Block, Bangalore',
    area: 'Koramangala',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6900,
    availableFor: 'All',
  },
  {
    pgname: 'Green Leaf PG',
    address: '48 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 6800,
    availableFor: 'Boys',
  },
  {
    pgname: 'Happy Homes',
    address: '18 Hinjewadi Phase 1, Pune',
    area: 'Hinjewadi',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 6600,
    availableFor: 'Girls',
  },
  {
    pgname: 'City Lights PG',
    address: '350 Andheri West, Mumbai',
    area: 'Andheri',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 6400,
    availableFor: 'All',
  },
  {
    pgname: 'The Nest',
    address: '95 Baner Road, Pune',
    area: 'Baner',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 7000,
    availableFor: 'Boys',
  },
  {
    pgname: 'Comfort Stay',
    address: '135 Koramangala 4th Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 7200,
    availableFor: 'Girls',
  },
  {
    pgname: 'Sunny Rooms',
    address: '60 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7300,
    availableFor: 'All',
  },
  {
    pgname: 'Safe Harbor PG',
    address: '25 Hinjewadi Phase 2, Pune',
    area: 'Hinjewadi',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 6800,
    availableFor: 'Boys',
  },
  {
    pgname: 'Relaxed Stay',
    address: '380 Andheri East, Mumbai',
    area: 'Andheri',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6700,
    availableFor: 'Girls',
  },
  {
    pgname: 'Blue Horizon PG',
    address: '120 Baner Road, Pune',
    area: 'Baner',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 6900,
    availableFor: 'All',
  },
  {
    pgname: 'Serene Stay',
    address: '200 Koramangala 6th Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7100,
    availableFor: 'Boys',
  },
  {
    pgname: 'Peace Haven PG',
    address: '70 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7000,
    availableFor: 'Girls',
  },
  {
    pgname: 'Quiet Corner',
    address: '30 Hinjewadi Phase 3, Pune',
    area: 'Hinjewadi',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6800,
    availableFor: 'All',
  },
  {
    pgname: 'Home Comfort PG',
    address: '400 Andheri West, Mumbai',
    area: 'Andheri',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 6500,
    availableFor: 'Boys',
  },
  {
    pgname: 'Sunset PG',
    address: '140 Baner Road, Pune',
    area: 'Baner',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 6900,
    availableFor: 'Girls',
  },
  {
    pgname: 'City Nest',
    address: '175 Koramangala 3rd Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7000,
    availableFor: 'All',
  },
  {
    pgname: 'Comfort Place',
    address: '85 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 7200,
    availableFor: 'Boys',
  },
  {
    pgname: 'Safe Haven',
    address: '50 Hinjewadi Phase 1, Pune',
    area: 'Hinjewadi',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 7100,
    availableFor: 'Girls',
  },
  {
    pgname: 'Sunny Days PG',
    address: '420 Andheri East, Mumbai',
    area: 'Andheri',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7300,
    availableFor: 'All',
  },
  {
    pgname: 'Urban Comfort',
    address: '130 Baner Road, Pune',
    area: 'Baner',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7200,
    availableFor: 'Boys',
  },
  {
    pgname: 'The Cozy Nest',
    address: '210 Koramangala 1st Block, Bangalore',
    area: 'Koramangala',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 7000,
    availableFor: 'Girls',
  },
  {
    pgname: 'Tranquil PG',
    address: '75 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 6800,
    availableFor: 'All',
  },
  {
    pgname: 'Quiet Stay',
    address: '40 Hinjewadi Phase 2, Pune',
    area: 'Hinjewadi',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 6600,
    availableFor: 'Boys',
  },
  {
    pgname: 'The Nest Inn',
    address: '450 Andheri West, Mumbai',
    area: 'Andheri',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 6500,
    availableFor: 'Girls',
  },
  {
    pgname: 'Golden Stay',
    address: '150 Baner Road, Pune',
    area: 'Baner',
    facilities: ['AC', 'Study Table', '24x7 Security'],
    price: 6900,
    availableFor: 'All',
  },
  {
    pgname: 'Happy Nest PG',
    address: '195 Koramangala 4th Block, Bangalore',
    area: 'Koramangala',
    facilities: ['Mess', 'Geyser', 'Power Backup'],
    price: 7000,
    availableFor: 'Boys',
  },
  {
    pgname: 'Cozy Inn',
    address: '90 Whitefield Main Road, Bangalore',
    area: 'Whitefield',
    facilities: ['Fridge', 'CCTV', 'Housekeeping'],
    price: 7200,
    availableFor: 'Girls',
  },
  {
    pgname: 'Safe Nest',
    address: '55 Hinjewadi Phase 3, Pune',
    area: 'Hinjewadi',
    facilities: ['Wi-Fi', 'Laundry', 'Parking'],
    price: 7100,
    availableFor: 'All',
  },
]

async function main() {
  for (const pg of dummyPGs) {
    await prisma.pG.create({
      data: {
        pgname: pg.pgname,
        address: pg.address,
        area: pg.area,
        facilities: { set: pg.facilities },
        price: pg.price,
        availableFor: pg.availableFor,
      },
    })
  }

  console.log('50 PGs seeded')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
